import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google"
import {AuthProvider} from "@/enteties/auth/auth-provider";

const manrope = Manrope({
    subsets: ["latin"],
    display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} antialiased`}
      >
      <AuthProvider>
          {children}
      </AuthProvider>

      </body>
    </html>
  );
}
