import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google"
import {Header} from "@/features/header/container/header";
import {Footer} from "@/features/footer/container/footer";

const manrope = Manrope({
    subsets: ["latin"],
    variable: "--font-manrope",
    display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
      >
      <Header/>
        {children}
      <Footer/>
      </body>
    </html>
  );
}
